### ISSUE TITLE
Arrow keys do not work, return undefined.

### ISSUE THREAD

**Issue by seanohue** [danarmstrong-io/MultiSnake#1]
Hey, my name is Sean, I work with Robb and he gave me this repo to look at to learn some more JavaScript. I noticed that the arrow keys do not work to control the snakes, so I forked the repo over and will be working on fixing that and/or building new features.

Thanks

**Comment by danarmstrong-io** [comment]
Hey actually currently WASD controls snake 1 and the arrow keys control snake 2. I never updated this in the controls tab. There is currently nothing in place preventing you from trying to control snakes that don't exist and so you get errors.
